// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FishStocks.Website.Data.FishStocks
{
    public partial class FishTransaction
    {
        public decimal? Price { get; set; }
        public DateTime DateEntered { get; set; }
        public long Id { get; set; }
        public string FishName { get; set; }
    }
}