// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FishStocks.Website.Data.FishStocks
{
    public partial class Fish
    {
        public string Name { get; set; }
        public long Id { get; set; }
    }
}